// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name)
VALUES 
  ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateUserParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllAuthors = `-- name: DeleteAllAuthors :exec
DELETE FROM users
`

func (q *Queries) DeleteAllAuthors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAuthors)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, created_at, updated_at 
FROM users
WHERE
  name = $1
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserNames = `-- name: ListUserNames :many
SELECT name
FROM users
`

func (q *Queries) ListUserNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
